### ISSUE TITLE
--methods option not found

### ISSUE THREAD

**Issue by popstheman** [NickSynev/make-observer-command#3]
Hey,
I tired using your command to create an observer with the methods options however I'm getting an error "--methods option not found".

**Comment by niksynov** [comment]
@popstheman Hello! Very strange, I have installed package on a clean project and made test, everything is working. Could you please provide your laravel version?

**Comment by popstheman** [comment]
Laravel version 5.6.33

I've solved my issue by tweaking observer.stub for the methods I need for now.

observer.stub (vendor/laravel/framework/src/Illuminate/Foundation/Console/stubs/observer.stub).
