### ISSUE TITLE
Add option to create service provider too

### ISSUE THREAD

**Issue by delmicio** [NickSynev/make-observer-command#5]
Hi,
Usually after creating an observer we need to add a service provider as well something like this...

App/Providers/StudentProfileModelServiceProvider.php
```PHP
<?php

namespace App\Providers;

use App\Models\StudentProfile;
use App\Observers\StudentProfileObserver;
use Illuminate\Support\ServiceProvider;

class StudentProfileModelServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        StudentProfile::observe(StudentProfileObserver::class);
    }
}
```

what do you think about adding a new option to generate this file as well?

**Comment by niksynov** [comment]
@delmicio Hello, thanks for your feedback. I don't think that it is needed to set observation directly in custom service providers. Some people put it in model classes or either standard `AppServiceProvider`. So it is up to developers declare `observe` where they want.
